[phases.setup]
nixPkgs = ["php84", "php84Extensions.pdo", "php84Extensions.pdo_mysql", "php84Extensions.mbstring", "php84Extensions.xml", "php84Extensions.curl", "php84Extensions.tokenizer", "php84Extensions.bcmath", "php84Extensions.ctype", "php84Extensions.fileinfo", "php84Extensions.openssl", "php84Extensions.sqlite3", "php84Extensions.pdo_sqlite"]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev --no-interaction",
    "npm install",
    "npm run build",
    "php artisan migrate --force",
    "php artisan db:seed --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
